"""
METS-Manifest Generator fuer PAGE-XML Export.

Erzeugt METS-Dateien im Transkribus-kompatiblen Format.
Wird automatisch von page_xml_generator.py aufgerufen.

Aufruf (standalone):
    python -m scripts.layout.mets_generator --doc 2310
    python -m scripts.layout.mets_generator               # alle Docs
"""

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

from lxml import etree

# Projekt-Imports
sys.path.insert(0, str(Path(__file__).parent.parent.parent))
from scripts.config import PAGE_XML_DIR

# METS Namespaces
METS_NS = "http://www.loc.gov/METS/"
XLINK_NS = "http://www.w3.org/1999/xlink"
METS_NSMAP = {"mets": METS_NS, "xlink": XLINK_NS}


def generate_mets(doc_id, page_xml_files):
    """Erzeugt METS-XML fuer ein Dokument.

    Args:
        doc_id: Dokument-ID
        page_xml_files: Sortierte Liste von PAGE-XML Dateinamen (relativ zu page/)

    Returns: lxml.etree.Element (mets:mets Root)
    """
    root = etree.Element("{%s}mets" % METS_NS, nsmap=METS_NSMAP)
    root.set("LABEL", doc_id)
    root.set("PROFILE", "zbz-ocr-tei")

    # metsHdr
    now = datetime.now(timezone.utc).isoformat()
    hdr = etree.SubElement(root, "{%s}metsHdr" % METS_NS)
    hdr.set("CREATEDATE", now)
    hdr.set("LASTMODDATE", now)

    agent = etree.SubElement(hdr, "{%s}agent" % METS_NS)
    agent.set("ROLE", "CREATOR")
    agent.set("TYPE", "ORGANIZATION")
    name = etree.SubElement(agent, "{%s}name" % METS_NS)
    name.text = "zbz-ocr-tei"
    note = etree.SubElement(agent, "{%s}note" % METS_NS)
    note.text = "Generated by page_xml_generator + mets_generator"

    # fileSec
    file_sec = etree.SubElement(root, "{%s}fileSec" % METS_NS)
    file_grp_master = etree.SubElement(file_sec, "{%s}fileGrp" % METS_NS)
    file_grp_master.set("ID", "MASTER")

    file_grp_page = etree.SubElement(file_grp_master, "{%s}fileGrp" % METS_NS)
    file_grp_page.set("ID", "PAGEXML")

    for seq, filename in enumerate(page_xml_files, 1):
        file_el = etree.SubElement(file_grp_page, "{%s}file" % METS_NS)
        file_el.set("ID", f"PAGEXML_{seq}")
        file_el.set("SEQ", str(seq))
        file_el.set("MIMETYPE", "application/xml")
        file_el.set("CREATED", now)

        flocat = etree.SubElement(file_el, "{%s}FLocat" % METS_NS)
        flocat.set("LOCTYPE", "OTHER")
        flocat.set("OTHERLOCTYPE", "FILE")
        flocat.set("{%s}type" % XLINK_NS, "simple")
        flocat.set("{%s}href" % XLINK_NS, f"page/{filename}")

    # structMap
    struct_map = etree.SubElement(root, "{%s}structMap" % METS_NS)
    struct_map.set("ID", "STRUCT_MAP")
    struct_map.set("TYPE", "MANUSCRIPT")

    doc_div = etree.SubElement(struct_map, "{%s}div" % METS_NS)
    doc_div.set("ID", "DOC_DIV")

    for seq, filename in enumerate(page_xml_files, 1):
        page_div = etree.SubElement(doc_div, "{%s}div" % METS_NS)
        page_div.set("ID", f"PAGE_{seq}")
        page_div.set("ORDER", str(seq))
        page_div.set("TYPE", "SINGLE_PAGE")

        fptr = etree.SubElement(page_div, "{%s}fptr" % METS_NS)
        area = etree.SubElement(fptr, "{%s}area" % METS_NS)
        area.set("FILEID", f"PAGEXML_{seq}")

    return root


def write_mets(doc_id, page_xml_dir=None):
    """Erzeugt METS fuer ein Dokument und schreibt die Datei.

    Args:
        doc_id: Dokument-ID
        page_xml_dir: Basis-Verzeichnis (default: PAGE_XML_DIR / doc_id)

    Returns: Path zur METS-Datei oder None
    """
    if page_xml_dir is None:
        page_xml_dir = PAGE_XML_DIR / doc_id

    page_dir = page_xml_dir / "page"
    if not page_dir.exists():
        return None

    # PAGE-XML Dateien finden und sortieren
    xml_files = sorted(
        f.name for f in page_dir.glob("*.xml")
        if re.match(r'.+_p\d+\.xml$', f.name)
    )
    if not xml_files:
        return None

    root = generate_mets(doc_id, xml_files)

    mets_path = page_xml_dir / "mets.xml"
    tree = etree.ElementTree(root)
    tree.write(
        str(mets_path),
        xml_declaration=True,
        encoding="UTF-8",
        pretty_print=True,
    )

    return mets_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="METS-Manifest Generator fuer PAGE-XML Export"
    )
    parser.add_argument("--doc", help="Einzelnes Dokument (z.B. 2310)")
    args = parser.parse_args()

    if args.doc:
        result = write_mets(args.doc)
        if result:
            print(f"  METS generiert: {result}")
        else:
            print(f"  Keine PAGE-XML Dateien fuer {args.doc}")
    else:
        # Alle Docs mit PAGE-XML
        if not PAGE_XML_DIR.exists():
            print("Kein PAGE-XML Verzeichnis vorhanden.")
            return

        total = 0
        for d in sorted(PAGE_XML_DIR.iterdir()):
            if d.is_dir() and d.name.isdigit():
                result = write_mets(d.name)
                if result:
                    total += 1
        print(f"Gesamt: {total} METS-Dateien generiert")


if __name__ == "__main__":
    main()
